### ISSUE TITLE
LOST ALL MY COINS? NEED HELP

### ISSUE THREAD

**Issue by alfreakaalbo** [dogecoin/dogecoin.com#115]
Hi guys,
 I have a problem with dogecoin wallet (android version from the official website)
I back up  my wallet on 25/01 and then the 28/1I bought 230k coins but I forgot to back up the wallet with this transaction..
 Then the 31/1 I bought 24k coins and my wallet wasn't synching on the last transaction and I start to panic...so I uninstall the app and I reinstall it.. and I restore the 25/1 backup wallet( as the only one I made) but still not coins..
Have I lose them all?
Now my wallet its synching and its 18 months behind at the moment.. I'm really scared..
I don't know what to do..
I've all the wallet ID of the 230k transaction and also all the blockchain info trough changelly.com can someone help me pls?
I dont want to lose my coins as I bought them at 1.1..

**Comment by MarcoPNS** [comment]
First of all: Wrong place! Please close this.

You should check out https://github.com/langerhans/dogecoin-wallet-new

You need to wait till your wallet is in sync. otherwise the transaction will not be displayed. Currently there is a problem with the sync because there is a big amount of new users.

**Comment by alfreakaalbo** [comment]
So even if i

**Comment by alfreakaalbo** [comment]
Sorry man..
Thank you very  much..
