### ISSUE TITLE
Please revert title of "XDP Wallet" to "DogeWallet"

### ISSUE THREAD

**Issue by nutildah** [dogecoin/dogecoin.com#330]
In the "Wallets" portion of Dogecoin.com, the name of the DogeWallet (Dogeparty wallet) was changed from "Doge Wallet" to "XDP Wallet" at some time after Mar 12 of this year.

https://web.archive.org/web/20230312163442/https://dogecoin.com/wallets/

The correct name of the wallet is "DogeWallet". The GitHub for this wallet is the first result that appears in a Google search for "dogewallet". It has never been referred to as "XDP Wallet" and may introduce confusion among people seeking out the DogeWallet. Thank you.

![image](https://user-images.githubusercontent.com/7720163/233828107-98c1ecfd-96f3-4590-a4e7-faf5c169cb3f.png)
![image](https://user-images.githubusercontent.com/7720163/233828123-5601452a-848d-4361-b165-fe30009a5809.png)

**Comment by cojohen** [comment]
This issue was corrected with this PR (note the different repo): https://github.com/dogecoinfoundation/dogecoin.com/pull/293

https://github.com/dogecoinfoundation/dogecoin.com/issues/288 closes this issue, though it has not been formally closed yet, the PR is merged and the changes are deployed.

Commit for relevant change **before**: (~4 months ago) https://github.com/dogecoinfoundation/dogecoin.com/blame/67b024ec544640403b97dce346fadb7473ca8da3/content/de/wallets/XDPWallet.md#L4

Commit for relevant change **after** : (~1 week ago)
https://github.com/dogecoinfoundation/dogecoin.com/blame/a6dfef8c799fd2356e43e14185f7d38372bb86be/content/no/wallets/DogepartyWallet.md#L4
